name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 14.5.0
        
    - name: Npm Install
      run: npm install

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 14.5.0
        
    - name: Npm Install
      run: npm install

    - name: Publish if version has been updated
      uses: pascalgn/npm-publish-action@1.3.4
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}